# Generated by Django 5.1.15 on 2026-05-12 00:38

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email_alter_user_personal_code_hash_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='jobposting',
            name='idx_job_posting_embedding',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='embedding',
        ),
        migrations.AddField(
            model_name='cvskill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvskill',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='cvskill',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard skill'), ('soft', 'Soft skill')], default='hard', max_length=8),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard skill'), ('soft', 'Soft skill')], default='hard', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cvskill',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_cv_skill_embedding', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='jobpostingskill',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='idx_job_posting_skill_embedding', opclasses=['vector_cosine_ops']),
        ),
    ]
