# Generated by Django 5.1.15 on 2026-05-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_jobposting_idx_job_posting_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvskill',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard skill'), ('soft', 'Soft skill'), ('experience', 'Experience')], default='hard', max_length=16),
        ),
        migrations.AlterField(
            model_name='jobpostingskill',
            name='type',
            field=models.CharField(choices=[('hard', 'Hard skill'), ('soft', 'Soft skill'), ('experience', 'Experience')], default='hard', max_length=16),
        ),
    ]
