# Generated by Django 5.1.15 on 2026-05-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cvskill_type_alter_jobpostingskill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvskill',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
