# Generated by Django 5.1.15 on 2026-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cvskill_type_alter_jobpostingskill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='workplace_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote')], default='on_site', max_length=16),
        ),
    ]
