# Generated by Django 5.1.15 on 2026-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobposting_workplace_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobpostingskill',
            name='job_posting_skill_unique',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobpostingskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='jobpostingskill',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='jobpostingskill',
            constraint=models.UniqueConstraint(fields=('job_posting', 'name'), name='job_posting_skill_unique'),
        ),
    ]
