# Generated by Django 5.1.15 on 2026-05-12 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_yoe_to_cvskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCVPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_key', models.CharField(max_length=512)),
                ('skills_data', models.JSONField()),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_cv_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
