# Generated by Django 5.1.15 on 2026-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_company_address_company_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_code',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
