# Generated by Django 5.1.15 on 2026-05-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_pending_cv_payment'),
        ('api', '0010_alter_company_registration_code'),
    ]

    operations = [
    ]
