# Generated by Django 5.1.15 on 2026-05-24 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_flatten_cvskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='api.cv')),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='api.jobposting')),
            ],
            options={
                'indexes': [models.Index(fields=['cv', '-score'], name='idx_match_score_cv_score')],
                'constraints': [models.UniqueConstraint(fields=('job_posting', 'cv'), name='match_score_unique'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='match_score_value_range')],
            },
        ),
    ]
