# Generated by Django 5.1.15 on 2026-05-24 22:26

from django.db import migrations, models


def drop_reviewed_status(apps, schema_editor):
    Application = apps.get_model('api', 'Application')
    Application.objects.filter(status='reviewed').update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_matchscore'),
    ]

    operations = [
        migrations.RunPython(drop_reviewed_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=16),
        ),
    ]
